// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CASOPRUEBA06Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void cASOPRUEBA06() {
    driver.get("https://www.choucairtesting.com/servicio/");
    driver.manage().window().setSize(new Dimension(1382, 754));
    driver.findElement(By.cssSelector(".search-icon")).click();
    driver.findElement(By.name("s")).click();
    driver.findElement(By.name("s")).sendKeys("calidad");
    driver.findElement(By.name("s")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".search-icon-path")).click();
    driver.findElement(By.name("s")).click();
    driver.findElement(By.cssSelector(".search-form:nth-child(1) .search-field")).click();
    driver.findElement(By.cssSelector(".search-form:nth-child(1) .search-field")).sendKeys("software");
    driver.findElement(By.cssSelector(".search-form:nth-child(1) .search-field")).sendKeys(Keys.ENTER);
    {
      WebElement element = driver.findElement(By.cssSelector(".search-icon"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".search-icon")).click();
    driver.findElement(By.name("s")).click();
    driver.findElement(By.cssSelector(".search-form:nth-child(1) .search-field")).click();
    driver.findElement(By.cssSelector(".search-form:nth-child(1) .search-field")).click();
  }
}
