// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CASOPRUEBA02Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void cASOPRUEBA02() {
    driver.get("https://www.choucairtesting.com/servicio/");
    driver.manage().window().setSize(new Dimension(1382, 754));
    driver.findElement(By.linkText("Servicios")).click();
    driver.findElement(By.linkText("Industrias")).click();
    driver.findElement(By.linkText("Servicios")).click();
    driver.findElement(By.linkText("Formación")).click();
    driver.findElement(By.linkText("Servicios")).click();
    driver.findElement(By.linkText("Comunidad")).click();
    driver.findElement(By.linkText("Servicios")).click();
    driver.findElement(By.linkText("Empleos")).click();
    driver.findElement(By.linkText("Servicios")).click();
    driver.findElement(By.linkText("Nosotros")).click();
    driver.findElement(By.linkText("Servicios")).click();
    driver.findElement(By.linkText("Contáctenos")).click();
    driver.findElement(By.linkText("Servicios")).click();
  }
}
